/**
 * Goals -> Strategies -> Interventions
 * All Strategies and Interventions point to a goal card by id
 * With the parent as reference point, each card type is associated with the others
 * There is no need for interventions to formally/directly relate to strategies
 */
var BACKUP = [
    {
        name: 'Informed Consent',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'GOALS',
        body: 'Gain informed consent and commitment to therapy',
        id: 'ca55ca4a-6b57-46ca-a696-749ad569dc72',
    },
    {
        name: 'Necessary Knowledge',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'STRATEGIES',
        body: 'Develop knowledge necessary for informed consent',
        id: '5c39e5c7-c3f6-4f15-9e9b-3a92195b55ef',
        parent: 'ca55ca4a-6b57-46ca-a696-749ad569dc72',
    },
    {
        name: 'Therapy Contract',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'STRATEGIES',
        body: 'Develop therapy contract',
        id: 'beed1d81-cbc1-46e8-ba40-f13fe6f1f471',
        parent: 'ca55ca4a-6b57-46ca-a696-749ad569dc72',
    },
    {
        name: 'Alternative Treatments',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Address alternative treatments that are available',
        id: 'ca8ddd8f-a157-478e-bac6-c37aef4f7475',
        parent: 'ca55ca4a-6b57-46ca-a696-749ad569dc72',
    },
    {
        name: 'Risks vs Benefits',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Address risks and benefits',
        id: '9657a8e8-4ab7-4d9d-8c7a-efe8684aa796',
        parent: 'ca55ca4a-6b57-46ca-a696-749ad569dc72',
    },
    {
        name: 'Planned Review',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Propose a specific time frame to review progress (models reality based tracking)',
        id: '88f88331-22ce-4524-b3b4-86ad2d4ce2b7',
        parent: 'ca55ca4a-6b57-46ca-a696-749ad569dc72',
    },
    {
        name: 'Role Orientations',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Orient the person to therapist and client roles',
        id: '67f5e171-2de7-4fda-a146-242d715be377',
        parent: 'ca55ca4a-6b57-46ca-a696-749ad569dc72',
    },
    {
        name: 'The Change Agenda',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'GOALS',
        body: 'Describe the clients change agenda and how it hasnt worked',
        id: 'f212b538-530f-4e02-98c2-cf6d71774927',
    },
    {
        name: 'Experience with the Problem',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'STRATEGIES',
        body: 'Detailed discussions of the clients experience of/with the problem',
        id: 'ad0f07d3-6b79-4f30-9e0a-21070f3a96dc',
    },
    {
        name: 'Problem evaluation',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'STRATEGIES',
        body: 'Help the client to evaluate their experience in connection to workability, vitality and normalisation',
        id: 'a2c57c41-92a2-458e-9554-5ffe6036e840',
    },
    {
        name: 'What do you want from life?',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'What do you want from life?',
        id: '64ea4161-e0fb-4f5a-85b8-00f951b1aadb',
    },
    {
        name: 'How has it worked?',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'How has it worked?',
        id: 'ffdda8e5-f4a9-49a3-bb0b-af06cc57787c',
    },
    {
        name: 'Undermining the Change Agenda',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'GOALS',
        body: 'Undermine client attachement to change agenda',
        id: 'ee1c5f7f-ef21-48be-8e70-750c1cc825a7',
    },
    {
        name: 'Willingness for the alternative',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'GOALS',
        body: 'Engender willingness to abandon the unworkable change agenda',
        id: '96cfdcc8-97bf-4ffd-8524-d508b7afdc44',
    },
    {
        name: 'Undermining Verbal Understanding',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'GOALS',
        body: 'Directly undermining *understanding* that is useless or unworkable',
        id: '0cedb0c0-628b-461c-b5d7-411a0ae613ec',
    },
    {
        name: 'Undermine Change Hopelessness',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'GOALS',
        body: 'Offering the alternative as reality based, incremental, measurable',
        id: '4a49e8df-e89f-4d55-aa5e-bdb0eb13b508',
    },
    {
        name: 'Introducing Workability',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'STRATEGIES',
        body: 'Develop workability as a yardstick',
        id: 'f11da5af-1304-49b6-9a38-b6a5fc03905e',
    },
    {
        name: 'Evoke creative hopelessness',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'STRATEGIES',
        body: 'Evoke creative hopelessness',
        id: '97d34a09-a452-4e29-82c5-7d5846810de8',
    },
    {
        name: 'Distinguish blame from responsibility',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'STRATEGIES',
        body: 'Distinguish blame from responsibility',
        id: '2d064bf9-d24b-4215-9254-3b8ccbaca202',
    },
    {
        name: 'Destablising Understanding',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'STRATEGIES',
        body: 'Use paradox, confusion and deliteralisation to destablise old verbal tracks that claim *understanding*',
        id: 'ad4e91d3-4ce9-4778-aecd-5206baa9f3ca',
    },
    {
        name: 'Hopelessness vs Future Workability',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'STRATEGIES',
        body: 'Distinguish between current feelings of hopelessness to eventual workability',
        id: '3e102457-02b9-45d2-9e4e-4ee13215bb40',
    },
    {
        name: 'Claiming the New Agenda',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'STRATEGIES',
        body: 'Avoid the old agenda; claiming the new',
        id: '7840101d-90a1-4329-8072-5d5b06a130ca',
    },
    {
        name: 'Focus on workability',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Focus on workability',
        id: 'effa7c83-0bf0-476e-9a44-a964f8c9a593',
    },
    {
        name: 'Talking to describe vs talking to make a difference',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Talking to describe vs talking to make a difference',
        id: 'ee32524a-3e72-404a-8904-9fbbc626f91d',
    },
    {
        name: 'Use of paradox',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Use of paradox',
        id: 'f1d662eb-379b-4025-aa38-389c82ca2a1b',
    },
    {
        name: 'Use of metaphor',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Use of metaphor',
        id: '7d1a116d-719f-4f16-8647-c2d9dec1ef4b',
    },
    {
        name: 'Man in the Hole Metaphor',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Man in the Hole Metaphor',
        id: '78db2922-7149-4ef3-bfae-020f8f20973c',
    },
    {
        name: 'Chinese Handcuffs Metaphor',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Chinese Handcuffs Metaphor',
        id: '9f86ad6b-f9cc-4c50-a2f9-0b918464e5ad',
    },
    {
        name: 'Feedback Screech Metaphor',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Feedback Screech Metaphor',
        id: '76468618-b43b-440a-954a-dfe7a8d220bd',
    },
    {
        name: 'Tug-of-War Metaphor',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Tug-of-War Metaphor',
        id: 'e2c03947-6de3-462b-a067-dc818f47925d',
    },
    {
        name: 'Learned Skill Metaphors',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Learned Skill Metaphors (e.g. playing music, dancing, games)',
        id: '06cbd1bc-4d8c-4c00-a848-ec0f6e77b388',
    },
    {
        name: 'How does that work for you?',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'How does that work for you?',
        id: '16771e7c-9a46-4ec4-9807-5c4fb8d61f15',
    },
    {
        name: 'Tailored interventions',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Inteventions tailored to client feedback',
        id: '3163be1d-6660-48ad-8ba3-ed6b7bbb32f1',
    },
    {
        name: 'Defocus on hopelessness',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Defocus on hopelessness as belief or feeling; focus on experienced effectss of change efforts',
        id: '6c66495d-62e7-497f-9336-7ebc51565a67',
    },
    {
        name: 'Proscribe change efforts',
        phase: 'CREATIVE_HOPELESSNESS',
        card: 'INTERVENTIONS',
        body: 'Proscribe change efforts',
        id: '16e0c129-5824-49a3-b2f8-99eae7de141e',
    },
];
